jobs:
- job: AlmOctanePipelineStart
  condition: always()
  steps:
  - task: octane-start-task@1
    inputs:
      OctaneServiceConnection: 'github-ado-alm'
      WorkspaceList: '9001'

- job: A
  dependsOn: AlmOctanePipelineStart
  steps:
  - bash: echo "A"

- job: B
  dependsOn: AlmOctanePipelineStart
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

- job: AlmOctanePipelineEnd
  condition: always()
  dependsOn:
  - AlmOctanePipelineStart
  - A
  - B
  steps:
  - task: octane-end-task@1
    inputs:
      OctaneServiceConnection: 'github-ado-alm'
      WorkspaceList: '9001'
